TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

GEN_PROFILES = ["STUDENT",
                "BUSINESS",
                "FAMILY",
                "OFFICE",
                "SPORT",
                "RANDOM"]

FORM_QUESTIONS = {
    0: 'ID',
    1: 'Godzina rozpoczecia',
    2: 'Godzina ukonczenia',
    3: 'Adres e-mail',
    4: 'Nazwa',
    5: 'Ile srednio kilometrow przemierzasz autem w skali roku?',
    6: 'Jaki jest Twoj przewazajacy tryb jazdy samochodem?',
    7: 'Jaki jest typ drog uczeszczanych w dlugich trasach?',
    8: 'Poszukujesz samochodu przeznaczonego dla ...?',
    9: 'Jak czesto jezdzisz samochodem na wycieczki lub wakacje?',
    10: 'Jaki jest Twoj budzet na zakup nowego samochodu?',
    11: 'Jak dlugo planujesz posiadac zakupiony samochod?',
    12: 'Podaj kod pocztowy twojego miejsca zamieszkania.',
    13: 'Czy wystepuja u Ciebie problemy ze zdrowiem mogace miec wplyw na komfort jazdy?',
    14: 'Zaznacz jakie problemy zdrowotne Cie dotycza:',
    15: 'Podaj swoj wzrost:',
    16: 'Czy zamierzasz przewozic zwierzeta?',
    17: 'W jaki sposob zamierzasz przewozic zwierzeta?',
    18: 'Czy zamierzasz przewozic rowery?',
    19: 'Na jakie sposoby chcialbys miec mozliwosc transportu rowerow?',
    20: 'Czy zamierzasz przewozic narty lub snowboard?',
    21: 'Na jakie sposoby chcialbys miec mozliwosc transportu nart lub snowboardu?',
    22: 'Jakie inne rzeczy bedziesz przewozic?',
    23: 'Jesli zamierzasz holowac przyczepe prosze zaznacz jakie rodzaje przyczep to beda?',
    24: 'Jak istotny jest dla Ciebie koszt paliwa?',
    25: 'Jak wazne jest dla Ciebie bezpieczenstwo?',
    26: 'Jak wazny jest dla Ciebie komfort jazdy?',
    27: 'Jak wazna jest dla Ciebie latwosc parkowania?',
    28: 'Jak wazna jest dla Ciebie dynamika jazdy?',
    29: 'Jaki rodzaj nadwozia preferujesz?',
    30: 'Jaki rodzaj silnika preferujesz?',
    31: 'Jaki rodzaj paliwa preferujesz?',
    32: 'Jaki rodzaj hybrydy preferujesz?',
    33: 'Jaki rodzaj przeniesienia napedu preferujesz?',
    34: 'Zaznacz preferowane marki :',
    35: 'Podaj preferencje co do wykonczenia wnetrza:',
    36: 'Wybierz preferowane dodatkowe wyposazenie',
    37: 'Wybierz preferowane systemy wspomagania :',
    38: 'Wybierz samochod, ktory wedlug Ciebie spelni Twoje oczekiwania:',
    39: 'Czy wazniejsza jest dla Ciebie jakosc czy cena czesci samochodowych?',
    40: 'Czy zamienna czesc, ktora kupujesz, musi byc idealnym zamiennikiem czesci producenta?'}

BUDGET_CLSS = {
    1: 'do 50 tys.',
    2: '50 - 75 tys.',
    3: '75 - 100 tys.',
    4: '100 - 150 tys.',
    5: '150 - 200 tys.',
    6: '200 - 250 tys.',
    7: 'powyzej 250 tys.'
}

CAR_MAKE_BODY_MODELS = {
    'Dacia': {
        'hatchback': ['Sandero'],
        'sedan': ['Logan'],
        'kombi': ['Logan', 'Duster'],
        'minivan': ['Lodgy'],
        'SUV': ['Duster'],
        'crossover': ['Duster', 'Sandero Stepway'],
        'coupe': ['Logan'],
        'cabrio': [],
        'dostawczy': ['Dokker Van'],
        'pickup': ['Duster'],
        'elektryczny': []
    },
    'Skoda': {
        'hatchback': ['Fabia', 'Scala', 'Citigo'],
        'sedan': ['Octavia', 'Superb'],
        'kombi': ['Fabia', 'Octavia', 'Scala'],
        'minivan': [],
        'SUV': ['Kamiq', 'Karoq', 'Kodiaq'],
        'crossover': ['Kamiq', 'Karoq', 'Kodiaq'],
        'coupe': ['Octavia'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['Enyaq iV']
    },
    'Fiat': {
        'hatchback': ['500', 'Panda', 'Tipo'],
        'sedan': ['Tipo'],
        'kombi': ['500L', 'Doblo'],
        'minivan': ['500L', 'Talento'],
        'SUV': ['500X'],
        'crossover': ['Panda', '500X'],
        'coupe': [],
        'cabrio': ['500'],
        'dostawczy': ['Ducato', 'Talento'],
        'pickup': [],
        'elektryczny': ['500']
    },
    'Kia': {
        'hatchback': ['Ceed', 'Picanto', 'Stonic', 'Rio', 'Soul', 'ProCeed'],
        'sedan': ['Rio', 'Stinger'],
        'kombi': ['Ceed', 'Sorento'],
        'minivan': [],
        'SUV': ['Sorento', 'Sportage'],
        'crossover': ['Stonic', 'XCeed', 'Niro', 'Soul'],
        'coupe': ['Stinger'],
        'cabrio': ['XCeed'],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['e-Niro', 'e-Soul']
    },
    'Hyundai': {
        'hatchback': ['i10', 'i20', 'i30', 'Kona'],
        'sedan': ['i40'],
        'kombi': ['i30', 'i40'],
        'minivan': [],
        'SUV': ['Santa Fe', 'Tucson'],
        'crossover': ['Kona', 'Santa Fe'],
        'coupe': ['Genesis'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['Kona', 'Kona electric', 'IONIQ']
    },
    'Renault': {
        'hatchback': ['Clio', 'Megane', 'Zoe'],
        'sedan': ['Megane', 'Talisman'],
        'kombi': ['Megane', 'Talisman'],
        'minivan': ['Espace', 'Grand Scenic', 'Trafic'],
        'SUV': ['Kadjar', 'Koleos'],
        'crossover': ['Captur', 'Kadjar'],
        'coupe': ['Megane'],
        'cabrio': ['Clio'],
        'dostawczy': ['Master', 'Trafic'],
        'pickup': ['Master'],
        'elektryczny': ['Zoe']
    },
    'Seat': {
        'hatchback': ['Ibiza', 'Leon'],
        'sedan': [],
        'coupe': [],
        'kombi': ['Leon'],
        'minivan': [],
        'SUV': ['Tarraco'],
        'crossover': ['Arona', 'Ateca'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': []
    },
    'Ford': {
        'hatchback': ['Fiesta', 'Focus'],
        'sedan': ['Focus', 'Mondeo'],
        'kombi': ['Focus', 'Mondeo', 'S-Max'],
        'minivan': ['S-Max', 'Galaxy', 'C-Max', 'Tourneo'],
        'SUV': ['Puma', 'Kuga', 'Edge'],
        'crossover': ['EcoSport', 'Puma', 'Kuga'],
        'coupe': ['Focus', 'Mustang'],
        'cabrio': [],
        'dostawczy': ['Tourneo', 'Transit'],
        'pickup': ['F150', 'Ranger Raptor'],
        'elektryczny': ['Mustang Mach-E']
    },
    'Suzuki': {
        'hatchback': ['Swift'],
        'sedan': [],
        'kombi': ['Swace'],
        'minivan': [],
        'SUV': ['SX4 S-Cross', 'Vitara'],
        'crossover': ['Ignis', 'SX4 S-Cross', 'Across'],
        'coupe': [],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': []
    },
    'Volkswagen': {
        'hatchback': ['Golf', 'Polo', 'up!'],
        'sedan': ['Arteon', 'Passat'],
        'kombi': ['Caddy', 'Sharan', 'Touran'],
        'minivan': ['Caddy', 'Sharan', 'California', 'Caravelle'],
        'SUV': ['Amarok', 'Tiguan', 'Touareg'],
        'crossover': ['T-Cross', 'Tiguan', 'T-Roc'],
        'coupe': ['Arteon'],
        'cabrio': [],
        'dostawczy': ['Crafter', 'Transporter'],
        'pickup': ['Amarok'],
        'elektryczny': ['ID.3', 'ID.4', 'e-up!', 'e-Golf']
    },
    'Peugeot': {
        'hatchback': ['208', '308'],
        'sedan': ['508'],
        'kombi': ['508', 'Partner', 'Rifter'],
        'minivan': ['Expert', 'Partner', 'Rifter', 'Traveller'],
        'SUV': ['3008', '5008'],
        'crossover': ['2008', '3008'],
        'coupe': ['508'],
        'cabrio': [],
        'dostawczy': ['Expert', 'Partner'],
        'pickup': [],
        'elektryczny': []
    },
    'Opel': {
        'hatchback': ['Corsa', 'Insignia', 'Astra'],
        'sedan': ['Insignia'],
        'kombi': ['Insignia', 'Astra'],
        'minivan': ['Combo', 'Zafira'],
        'SUV': ['Grandland X'],
        'crossover': ['Crossland X', 'Mokka'],
        'coupe': [],
        'cabrio': [],
        'dostawczy': ['Vivaro'],
        'pickup': [],
        'elektryczny': ['Mokka-e']
    },
    'Mitsubishi': {
        'hatchback': ['Eclipse', 'Space Star'],
        'sedan': [],
        'kombi': [],
        'minivan': [],
        'SUV': ['Outlander'],
        'crossover': ['ASX', 'Eclipse Cross'],
        'coupe': [],
        'cabrio': [],
        'dostawczy': [],
        'pickup': ['L200'],
        'elektryczny': []
    },
    'Nissan': {
        'hatchback': ['Micra'],
        'sedan': [],
        'kombi': [],
        'minivan': ['NV200'],
        'SUV': ['X-Trail'],
        'crossover': ['Juke', 'Qashqai'],
        'coupe': ['370 Z'],
        'cabrio': ['Juke'],
        'dostawczy': [],
        'pickup': ['Navara'],
        'elektryczny': ['Leaf']
    },
    'Honda': {
        'hatchback': ['Civic', 'Jazz'],
        'sedan': [],
        'kombi': [],
        'minivan': [],
        'SUV': ['CR-V'],
        'crossover': ['HR-V', 'Jazz Crosstar'],
        'coupe': ['Civic Type R', 'NSX'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['e']
    },
    'Subaru': {
        'hatchback': ['Impreza'],
        'sedan': ['Impreza'],
        'kombi': [],
        'minivan': [],
        'SUV': ['Outback'],
        'crossover': ['XV', 'Forester'],
        'coupe': ['BRZ'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': []
    },
    'Toyota': {
        'hatchback': ['Aygo', 'Yaris', 'Corolla', 'Prius'],
        'sedan': ['Corolla', 'Camry'],
        'kombi': [],
        'minivan': ['Proace City Verso'],
        'SUV': ['RAV4', 'Land Cruiser'],
        'crossover': ['C-HR', 'RAV4'],
        'coupe': ['Supra'],
        'cabrio': [],
        'dostawczy': ['Proace'],
        'pickup': ['Hilux'],
        'elektryczny': []
    },
    'Mazda': {
        'hatchback': ['3'],
        'sedan': ['3', '6'],
        'kombi': ['6'],
        'minivan': [],
        'SUV': ['CX-30'],
        'crossover': ['CX-3', 'CX-5', 'MX-30'],
        'coupe': ['MX-5'],
        'cabrio': ['MX-5'],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['MX-30']
    },
    'Smart': {
        'hatchback': ['Fortwo', 'Forfour'],
        'sedan': [],
        'kombi': [],
        'minivan': [],
        'SUV': [],
        'crossover': [],
        'coupe': [],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['EQ Fortwo', 'EQ Forfour', 'Fortwo']
    },
    'Mini': {
        'hatchback': ['Cooper', 'Cooper S'],
        'sedan': [],
        'kombi': ['Clubman'],
        'minivan': [],
        'SUV': [],
        'crossover': ['Countryman'],
        'coupe': [],
        'cabrio': ['Cabrio'],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['Cooper SE']
    },
    'Alfa Romeo': {
        'hatchback': ['Giulietta'],
        'sedan': ['Giulia'],
        'kombi': [],
        'minivan': [],
        'SUV': ['Stelvio'],
        'crossover': ['Stelvio'],
        'coupe': ['Giulia'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': []
    },
    'Citroen': {
        'hatchback': ['C1'],
        'sedan': ['C5 Aircross', 'C5', 'C-Elysee'],
        'kombi': ['C5', 'Jumpy Combi'],
        'minivan': ['C4 Grand Picasso', 'SpaceTourer'],
        'SUV': ['C5 Aircross'],
        'crossover': ['C3', 'C3 Aircross', 'C4', 'Cactus', 'C4 Cactus'],
        'coupe': ['C4'],
        'cabrio': [],
        'dostawczy': ['Jumper'],
        'pickup': [],
        'elektryczny': []
    },
    'Jeep': {
        'hatchback': ['Renegade'],
        'sedan': [],
        'kombi': [],
        'minivan': [],
        'SUV': ['Cherokee', 'Gladiator', 'Renegade', 'Wrangler'],
        'crossover': ['Compass', 'Renegade', 'Wrangler'],
        'coupe': [],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': []
    },
    'Volvo': {
        'hatchback': [],
        'sedan': ['S60', 'S90'],
        'kombi': ['V40', 'V60', 'V90', 'XC90'],
        'minivan': ['XC90'],
        'SUV': ['XC60', 'XC90'],
        'crossover': ['XC40', 'S60 Cross Country', 'V60 Cross Country'],
        'coupe': [],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['XC40 Recharge', 'Polestar 1']
    },
    'Audi': {
        'hatchback': ['A1', 'A3', 'RS3', 'S3'],
        'sedan': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q8', 'RS3', 'S4', 'S5', 'S6', 'S7', 'S8'],
        'kombi': ['A3', 'A4', 'A6 Allroad', 'Q7', 'RS4', 'RS5', 'RS6', 'RS7', 'RS'],
        'minivan': [],
        'SUV': ['Q5', 'Q8', 'RS Q8', 'SQ5', 'SQ7', 'SQ8'],
        'crossover': ['A4 Allroad', 'Q2', 'Q3'],
        'coupe': ['R8', 'RS Q3'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['E-Tron']
    },
    'Lexus': {
        'hatchback': ['CT'],
        'sedan': ['ES', 'IS', 'LS'],
        'kombi': ['LS'],
        'minivan': [],
        'SUV': ['NX'],
        'crossover': ['UX', 'NX'],
        'coupe': ['LC', 'RC F'],
        'cabrio': ['LC 500 CV'],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['UX 300e']
    },
    "Infiniti": {
        'hatchback': [],
        'sedan': ['Q50'],
        'kombi': [],
        'minivan': [],
        'SUV': [],
        'crossover': [],
        'coupe': ['Q60'],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': []
    },
    "Jaguar": {
        'hatchback': [],
        'sedan': ['XE', 'XF'],
        'kombi': ['XF'],
        'minivan': [],
        'SUV': [],
        'crossover': ['E-Pace', 'F-Pace'],
        'coupe': ['F-Type'],
        'cabrio': ['F-Type'],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['I-Pace']
    },
    'Land Rover': {
        'hatchback': [],
        'sedan': [],
        'kombi': [],
        'minivan': [],
        'SUV': ['Defender', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Discovery', 'Range Rover Evoque'],
        'crossover': ['Range Rover Evoque', 'Discovery Sport'],
        'coupe': [],
        'cabrio': [],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': []
    },
    'BMW': {
        'hatchback': ['Seria 1'],
        'sedan': ['3GT', '6GT', 'M3', 'M4', 'M5', 'M8', 'Seria 2', 'Seria 3', 'Seria 4', 'Seria 5',
                  'Seria 6', 'Seria 7', 'Seria 8'],
        'kombi': [],
        'minivan': [],
        'SUV': ['X5', 'X5 M', 'X6', 'X6 M', 'X7', 'X2', 'X2', 'X2'],
        'crossover': ['X1', 'X2', 'X3', 'X3 M', 'X4'],
        'coupe': ['M2', 'Z4 M'],
        'cabrio': ['Z4', 'Z4 M'],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['i3', 'i4', 'iX', 'i3s']
    },
    'Mercedes': {
        'hatchback': ['Klasa A', 'Klasa B'],
        'sedan': ['CLA', 'CLS', 'Klasa C', 'Klasa E', 'Klasa S'],
        'kombi': ['CLA'],
        'minivan': ['Klasa V', 'Vito'],
        'SUV': ['GLB', 'GLE', 'GLS', 'Klasa G'],
        'crossover': ['EQC', 'GLA'],
        'coupe': ['AMG GT', 'GLC'],
        'cabrio': ['Klasa C', 'Klasa E'],
        'dostawczy': ['Sprinter'],
        'pickup': ['Klasa X'],
        'elektryczny': ['EQV']
    },
    'Porsche': {
        'hatchback': [],
        'sedan': ['Panamera'],
        'kombi': [],
        'minivan': [],
        'SUV': ['Cayenne'],
        'crossover': ['Macan'],
        'coupe': ['911', '718 Cayman'],
        'cabrio': ['911', '718 Boxster', '718 Spyder'],
        'dostawczy': [],
        'pickup': [],
        'elektryczny': ['Taycan'],
    },
    'Tesla': {'elektryczny': ['Model S', 'Model 3', 'Model X', 'Model Y']}
}

ELECTRIC_CAR_BODIES = {
    'hatchback': ['ID.3', 'ID.4', 'e-up!', 'e-Golf', 'Leaf', 'e', 'EQ Fortwo', 'EQ Forfour', 'Fortwo', 'i4', 'iX',
                  'i3s', 'e-Niro', 'e-Soul', 'Zoe'],
    'crossover': [
        'Mokka-e',
        'MX-30',
        'Cooper SE',
        'UX 300e',
        'EQC',
        'Model 3',
        'Enyaq iV',
        'Kona electric',
        'IONIQ',
        'Mustang Mach-E'],
    'SUV': [
        'E-Tron',
        'I-Pace',
        'Model X',
        'Model Y'],
    'sedan': [
        'XC40 Recharge',
        'Polestar 1',
        'Model S'],
    'dostawczy': ['EQV'],
    'coupe': ['Taycan']}

ZIP_CODES = {
    'mokotow': [
        '00-791',
        '02-716',
        '02-708',
        '02-677',
        '00-727',
        '02-761',
        '00-713',
        '00-720',
        '00-715',
        '00-707',
        '02-584',
        '02-654',
        '02-643',
        '02-551',
        '00-773',
        '02-547',
        '02-505',
        '00-774',
        '02-534',
        '00-701'],
    'rembertow': [
        '04-413',
        '04-424',
        '04-474',
        '04-277',
        '04-498',
        '04-428',
        '04-479',
        '04-421',
        '04-252',
        '00-910'],
    'bielany': [
        '01-934',
        '01-870',
        '01-696',
        '01-727',
        '01-940',
        '01-995',
        '01-934',
        '01-953',
        '01-928',
        '01-954'],
    'bemowo': [
        '01-376',
        '01-475',
        '01-493',
        '01-358',
        '01-480',
        '01-317',
        '01-493',
        '01-318',
        '01-497',
        '01-386'],
    'srodmiescie': [
        '00-117',
        '00-575',
        '00-654',
        '00-275',
        '00-229',
        '00-127',
        '00-454',
        '00-497',
        '00-656',
        '00-249',
        '00-117',
        '00-575',
        '00-654',
        '00-275',
        '00-229',
        '00-127',
        '00-454',
        '00-497',
        '00-656',
        '00-249'],
    'wlochy': [
        '02-490',
        '02-168',
        '02-441',
        '02-484',
        '02-468',
        '02-243',
        '02-490',
        '02-165',
        '02-267',
        '02-187'],
    'ursynow': [
        '02-775',
        '02-776',
        '02-796',
        '02-768',
        '02-797',
        '02-747',
        '02-776',
        '02-787',
        '02-829',
        '02-835',
        '02-973',
        '02-776',
        '02-790',
        '02-877',
        '02-814',
        '02-776',
        '02-784',
        '02-836',
        '02-790',
        '02-857'],
    'jozefow': [
        '05-410',
        '05-410',
        '05-410',
        '05-410',
        '05-410',
        '05-410',
        '05-410',
        '05-410',
        '05-410',
        '05-410'],
    'ochota': [
        '02-020',
        '02-024',
        '02-107',
        '02-382',
        '02-202',
        '02-369',
        '02-032',
        '02-056',
        '02-055',
        '02-396'],
    'praga': [
        '03-757',
        '03-732',
        '03-767',
        '03-454',
        '03-455',
        '03-710',
        '03-704',
        '03-774',
        '03-309',
        '03-461'],
}
